death/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("death_app.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]

death_app/urls.py
from django.urls import path
from death_app import views

from .views import index, registration_client, registration_employee, client_profile, employee_profile, employee_show, employee_delete, hall_add, hall_show, hall_delete, book_visit, get_available_time, visit_show_employee,visit_show_client, visit_update_client, visit_delete_client, visit_show_client, client_update,employee_update,hall_update,service_add,service_delete,service_show,service_update
urlpatterns = [
    path('', index, name='index'),

    # Регистрация клиентов и сотрудников
    path('registration/client/', registration_client, name='registration_client'),
    path('registration/employee/', registration_employee, name='registration_employee'),

    # Обновление профиля клиента и сотрудника
    path('client/update/', client_update, name='client_update'),
    path('employee/update/<int:employee_id>/', employee_update, name='employee_update'),

    # Профили клиента и сотрудника
    path('client/profile/', client_profile, name='client_profile'),
    path('employee/profile/', employee_profile, name='employee_profile'),

    # Управление сотрудниками
    path('employee/delete/<int:employee_id>/', employee_delete, name='employee_delete'),
    path('employee/show/', employee_show, name='employee_show'),

    # Управление залами
    path('hall/add/', hall_add, name='hall_add'),
    path('hall/show/', hall_show, name='hall_show'),
    path('hall/delete/<int:hall_id>/', hall_delete, name='hall_delete'),
    path('hall/update/<int:hall_id>/', hall_update, name='hall_update'),

    # Бронирование посещений
    path('book/visit/', book_visit, name='book_visit'),
    path('visit/show/', visit_show_employee, name='visit_show_employee'),
    path('visit/show/client/', visit_show_client, name='visit_show_client'),

    # Обновление и удаление визитов
    path('visit/update/<int:visit_id>/', visit_update_client, name='visit_update_client'),
    path('visit/delete/<int:visit_id>/', visit_delete_client, name='visit_delete_client'),
    path('get_available_time/', get_available_time, name='get_available_time'),

    # Управление услугами
    path('service/add/', service_add, name='service_add'),
    path('service/show/', service_show, name='service_show'),
    path('service/delete/<int:service_id>/', service_delete, name='service_delete'),
    path('service/update/<int:service_id>/', service_update, name='service_update'),
]

death_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils.timezone import now

# Create your models here.

# How cemetrries are stored 
class Cemetry(models.Model):

    # Cemetry has a name
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return f"{self.name}"

# How regions in cemetries are stored
class Region(models.Model):

    # Region has a name of cemetry and a region 
    cemetry = models.ForeignKey(Cemetry,on_delete=models.CASCADE)
    region = models.DecimalField(max_digits=10, decimal_places=0, unique=True)
    
    def __str__(self):
        return f"{str(self.cemetry)} участок №{self.region}"

# How material of monuments are stored
class Material(models.Model):

    # Material has a name
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.name}"

class Colour(models.Model):

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.name}"
    
class SizeofMonument(models.Model):

    length = models.DecimalField(max_digits=10, decimal_places=0)
    width = models.DecimalField(max_digits=10, decimal_places=0)
    height = models.DecimalField(max_digits=10, decimal_places=0)
    
    class Meta:
        unique_together = ('length', 'width', 'height')

    def __str__(self):
        return f"{self.length}*{self.width}*{self.height}"

class SizeofCurbstone(models.Model):

    length = models.DecimalField(max_digits=10, decimal_places=0)
    width = models.DecimalField(max_digits=10, decimal_places=0)
    height = models.DecimalField(max_digits=10, decimal_places=0)
    
    class Meta:
        unique_together = ('length', 'width', 'height')

    def __str__(self):
        return f"{self.length}*{self.width}*{self.height}"    

class Monument(models.Model):

    name = models.CharField(max_length=100)

    material = models.OneToOneField(Material, on_delete = models.CASCADE)
    colour = models.OneToOneField(Colour, on_delete = models.CASCADE)

    size = models.OneToOneField(SizeofMonument, on_delete = models.CASCADE)
    curbstone = models.OneToOneField(SizeofCurbstone, on_delete = models.CASCADE)
    
    class Meta:
        unique_together = ('name', 'material', 'colour', 'size', 'curbstone')

    def __str__(self):
        return f"{self.name} материал - {self.material}, цвет - {self.colour}, размер - {self.size}, размер тумбы - {self.curbstone}"

class Funeral(models.Model):

    name = models.CharField(max_length=100)

    date = models.DateField(default=now)  # Дата

    time = models.TimeField() # Время визита, строка в формате HH:MM

    cemetry = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='services')

    people = models.DecimalField(max_digits=10, decimal_places=0,null=True,blank=True)  
    image = models.URLField(null=True,blank=True)

    class Meta:
        unique_together = ('name', 'date', 'cemetry')

    def __str__(self):
        return f"Усопший: {self.name} вреемя похорон: {self.date}, кладбище - {self.cemetry}"

class Gravediggers(models.Model):

    name = models.CharField(max_length=100)

    start_time = models.TimeField()  # Начало рабочего дня

    end_time = models.TimeField()  # Конец рабочего дня

    def __str__(self):
        return f"{self.name}"

class Memorial(models.Model):

    name = models.CharField(max_length=100)

    location = models.CharField(max_length=255)  # Местоположение зала

    start_time = models.TimeField()  # Начало рабочего дня

    end_time = models.TimeField()  # Конец рабочего дня

    def __str__(self):
        return f"{self.name} по адресу: {self.location}"
    
class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='client')  # Пользователь

    patronymic = models.CharField(max_length=255)

    phone_number = models.CharField(max_length=255, blank=True, null=True, validators=[
        RegexValidator(r'^\+7\d{10}$', message='Номер телефона должен быть в формате +7XXXXXXXXXX')])  # Номер телефона

    email = models.EmailField()

    blood_type = models.CharField(max_length=10)  
    Rh_factor = models.CharField(max_length=10)  
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employee')  # Пользователь

    patronymic = models.CharField(max_length=255)

    phone_number = models.CharField(max_length=255, blank=True, null=True, validators=[
        RegexValidator(r'^\+7\d{10}$', message='Номер телефона должен быть в формате +7XXXXXXXXXX')])  # Номер телефона

    email = models.EmailField()
    
    position = models.CharField(max_length=255)  # Должность

    blood_type = models.CharField(max_length=10)  
    Rh_factor = models.CharField(max_length=10) 

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Works(models.Model):
    work = models.CharField(max_length=100)

    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='visits')  # Клиент

    gravediggers = models.OneToOneField(Gravediggers, on_delete=models.CASCADE)

    date = models.DateField(default=now)  # Дата

    time = models.TimeField() # Время визита, строка в формате HH:MM

    def save(self, *args, **kwargs):
        """Метод сохранения визита и автоматического выбора зала."""
        super(Works, self).save(*args, **kwargs) # Сохраняем визит

    def __str__(self):
        return f"{self.work} {self.date} {self.time}"

class Visit(models.Model):
    memorial = models.OneToOneField(Memorial, on_delete=models.CASCADE)

    date = models.DateField(default=now)  # Дата

    time = models.TimeField() # Время визита, строка в формате HH:MM

    def __str__(self):
        return f"{self.work} {self.date} {self.time}"

death_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User, Client, Employee, Funeral, Cemetry, Region, Gravediggers, Works
from datetime import datetime, timedelta
from .time_slots import get_time_slots

# Форма регистрации клиента
class ClientRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')

# Форма для регистрации клиента
class ClientForm(forms.ModelForm):

    BLOOD_TYPE_CHOICES = (
        ('I', 'I'),
        ('II', 'II'),
        ('III', 'III'),
        ('IV', 'IV'),
    )

    RH_FACTOR_CHOICES = (
        ('+', '+'),
        ('-', '-'),
    )

    username = forms.CharField(label='Логин', max_length=150)
    first_name = forms.CharField(label='Имя', max_length=150)
    last_name = forms.CharField(label='Фамилия', max_length=150)

    patronymic = forms.CharField(required=False, label='Отчество', max_length=150)

    phone_number = forms.CharField(label='Номер телефона', max_length=150)
    email = forms.EmailField(required=True)

    blood_type = forms.CharField(label='Группа крови', widget=forms.Select(choices=BLOOD_TYPE_CHOICES))
    Rh_factor = forms.CharField(label='Резус-фактор', widget=forms.Select(choices=RH_FACTOR_CHOICES))

    class Meta:
        model = Client
        fields = ['username', 'first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'blood_type', 'Rh_factor']
        labels = {
            'username': 'Логин',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'patronymic': 'Отчество', 
            'phone_number': 'Номер телефона', 
            'email': 'email', 
            'blood_type': 'Группа крови', 
            'Rh_factor': 'Резус-фактор'
        }

# Форма регистрации сотрудника
class EmployeeRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')

# Форма для добавления/редактирования данных сотрудника
class EmployeeForm(forms.ModelForm):

    BLOOD_TYPE_CHOICES = (
        ('I', 'I'),
        ('II', 'II'),
        ('III', 'III'),
        ('IV', 'IV'),
    )

    RH_FACTOR_CHOICES = (
        ('+', '+'),
        ('-', '-'),
    )

    username = forms.CharField(label='Логин', max_length=150)
    first_name = forms.CharField(label='Имя', max_length=150)
    last_name = forms.CharField(label='Фамилия', max_length=150)

    patronymic = forms.CharField(required=False, label='Отчество', max_length=150)

    phone_number = forms.CharField(label='Номер телефона', max_length=150)
    email = forms.EmailField(required=True)

    position = forms.CharField(label='Должность')

    blood_type = forms.CharField(label='Группа крови', widget=forms.Select(choices=BLOOD_TYPE_CHOICES))
    Rh_factor = forms.CharField(label='Резус-фактор', widget=forms.Select(choices=RH_FACTOR_CHOICES))
    
    class Meta:
        model = Employee
        fields = ['username', 'first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'position', 'blood_type', 'Rh_factor']
        labels = {
            'username': 'Логин',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'patronymic': 'Отчество', 
            'phone_number': 'Номер телефона', 
            'email': 'email', 
            'position': 'Должность',
            'blood_type': 'Группа крови', 
            'Rh_factor': 'Резус-фактор'
        }

class CemetryForm(forms.ModelForm):
    class Meta:
        model = Cemetry
        fields = ['name']
        labels = {
            'name': 'Название кладбища',
        }

class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = ['cemetry','region']
        labels = {
            'cemetry': 'Кладбища',
            'region': 'Номер участка',
        }

class FuneralForm(forms.ModelForm):

    date = forms.DateField(label='Дата  посещения',
                           widget=forms.DateInput(
                               attrs={'type': 'date', 'id': 'id_date', 'min': datetime.today().strftime('%Y-%m-%d'),

                                      'max': (datetime.today() + timedelta(days=7)).strftime('%Y-%m-%d')}))

    time = forms.TimeField(label='Время посещения',widget=forms.TimeInput(attrs={'type': 'time'}, format='%H'))

    class Meta:
        model = Funeral
        fields = ['name', 'date', 'time', 'cemetry', 'people', 'image']
        labels = {
            'name': 'Фио усопшего',
            'date': 'время похорон',
            'time': 'время похорон',
            'cemetry': 'Участок на кладбище',
            'people': 'Число присутствоваших',
            'image': 'Фото с похорон',
        }

        cemetry = forms.ModelChoiceField(queryset=Region.objects.all())

class GravediggersForm(forms.ModelForm):
    name = forms.CharField(max_length=100, label='Название бригады', )

    start_time = forms.TimeField(label='Начало работы зала',
                                 widget=forms.TimeInput(attrs={'type': 'time'}, format='%H'))

    end_time = forms.TimeField(label='Конец работы зала',
                               widget=forms.TimeInput(attrs={'type': 'time'}, format='%H'))
    
    class Meta:
        model = Gravediggers
        fields = ['name', 'start_time', 'end_time']
        labels = {
            'name': 'Название бригады',
            'start_time': 'Начало работы зала',
            'end_time': 'Конец работы зала',
        }

class WorksForm(forms.ModelForm):

    works_choices = (
        ('Похороны', 'Похороны'),
    )
    work = forms.CharField(label='Работы', widget=forms.Select(choices=works_choices))

    date = forms.DateField(label='Дата  посещения',
                           widget=forms.DateInput(
                               attrs={'type': 'date', 'id': 'id_date', 'min': datetime.today().strftime('%Y-%m-%d'),

                                      'max': (datetime.today() + timedelta(days=7)).strftime('%Y-%m-%d')}))

    time = forms.TimeField(label='Время посещения',widget=forms.TimeInput(attrs={'type': 'time'}, format='%H'))

    class Meta:
        model = Works
        fields = ['work', 'gravediggers', 'date','time']
        labels = {
            'work': 'Название бригады',
            'gravediggers': 'Начало работы зала',
            'date': 'Конец работы зала',
            'time': 'Конец работы зала',
        }

        gravediggers = forms.ModelChoiceField(queryset=Gravediggers.objects.all())

    def __init__(self, *args, **kwargs):  # args - список аргументов, kwargs - словарь аргументов
        super(WorksForm, self).__init__(*args, **kwargs)

        # Добавим доступные слоты времени в поле time
        if 'gravediggers' in self.data and 'date' in self.data:
            employee_id = self.data.get('gravediggers')
            date_id = self.data.get('date')

            gravediggers = Gravediggers.objects.get(id=employee_id)
            date = datetime.strptime(date_id, '%Y-%m-%d').date()

            available_time = get_time_slots(gravediggers, date)

            # Преобразуем список доступных временных слотов в choices для поля
            self.fields['time'].choices = [(slot, slot) for slot in available_time]

death_app/templates/update/client_update.html
{% extends 'index.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-7">Редактирование профиля</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!-- Карточка для редактирования профиля -->
            <div class="card">
                <div class="card-header text-center">
                    <h3>Обновление данных пользователя</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="id_username">Логин</label>
                            {{ client_data_form.username }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_first_name">Имя</label>
                            {{ client_data_form.first_name }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_last_name">Фамилия</label>
                            {{ client_data_form.last_name }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_email">Email</label>
                            {{ client_data_form.email }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_phone_number">Телефон</label>
                            {{ form.phone_number }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_date_of_birth">Дата рождения</label>
                            {{ form.date_of_birth }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_gender">Пол</label>
                            {{ form.gender }}
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                        <a href="{% url 'client_profile' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}

death_app/templates/update/employee_update.html
{% extends 'index.html' %}

{% block title %} Редактирование профиля сотрудника {% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Редактирование профиля сотрудника</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Обновление данных сотрудника</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}


                        <div class="form-group">
                            {{ form.as_p }}
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                        <a href="{% url 'employee_show' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

death_app/templates/update/hall_update.html
{% extends 'index.html' %}

{% block title %} Редактирование зала {% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Редактирование зала</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Обновление данных зала</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            {{ form.as_p }}
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                        <a href="{% url 'hall_show' %}" class="btn btn-secondary">Отмена</a>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

death_app/templates/update/service_update.html
{% extends 'index.html' %}

{% block title %} Редактирование услуги {% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Редактирование услуги</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">

            <div class="card">
                <div class="card-header text-center">
                    <h3>Обновление данных услуги</h3>
                </div>
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                        <a href="{% url 'service_show' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

death_app/templates/update/visit_update_client.html
{% extends 'index.html' %}

{% block title %} Редактирование моего визита {% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">

        <div class="col-md-7">
            <div class="card">
                <div class="card-header">Редактирование посещения</div>
                <div class="card-body">
                    <!-- Форма для редактирования визита -->
                    <form method="POST">

                        {% csrf_token %}

                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}

                        {{ form.as_p }}

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                            <a href="{% url 'visit_show_client' %}" class="btn btn-secondary">Назад к моим визитам</a>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}